### PR TITLE
PULL REQUEST to merge our branch (SLH) to the main branch (master)

### PR DESCRIPTION
**Pull request by AlexandreGrave**

### CODE REVIEW

**Comment by MarieEtienne** [comment]
Do not forget to solve conflicts and ask for review

**Comment by MarieEtienne** [comment]
I have erased your pull request. But to do so I had to rewrite history of the master branch. This will produce errors on your own versions but i had no other choices. The easiest way for you, is to clone again the repo on your computer at a different location. 
Then on your computer, on your branch 
1. merge master.
2. effectively solve the conflicts
3. open a pull request
4. be sure that all checks pass
5. Ask for approval from other before merging
It is not allowed to merge the PR with outside verification

**Comment by AlexandreGrave** [comment]
Ok I’ll try to do it now !

Thank you and sorry again

**Comment by MarieEtienne** [comment]
the sign of conflicts are still in 
image

**Comment by MarieEtienne** [comment]
Dans tous les cas, ne pas merger la PR sans accord extérieur

**Pull request merged**
