### PR TITLE
Pollen merging to master

### PR DESCRIPTION
**Pull request by BastienBerrand**
PULL REQUEST to merge our branch (Pollen) to the main branch (master)

### CODE REVIEW

**Comment by MarieEtienne** [comment]
Do not forget to solve the conflicts and ask for review

**Comment by EliaDroneau** [comment]
@MarieEtienne we have issues with the rmarkdown "ERROR: YAMLError: bad indentation of a mapping entry at line 11, column 16" we don't understand.

**Comment by MarieEtienne** [comment]
you just need to ask for review before merging now

**Review by AlexandreGrave — COMMENTED** [review]
Everything seem clear and well explained but I think there is conflicts at the end

**Review by KlerviChoulette — APPROVED** [review]

**Comment by S3B2ZO** [comment]
I think your pull request is good, there is no conflict

**Comment by MarieEtienne** [comment]
i guess you can merge your work

**Pull request merged**
