### PR TITLE
Merging nidification_main towards master 

### PR DESCRIPTION
**Pull request by rudyusach**
Correction of the YAML block in Analyse_Birds.qmd and merging of nidification_main towards master

### CODE REVIEW

**Comment by anaelleduplessis** [comment]
it seems that there is still conflicts that must be solved

**Comment by MarieEtienne** [comment]
You should not add generated files to the versionning system all files [Analyse_Birds_files. I have removed thos files from the versionning and specify in .giitignore to ignore them

**Comment by MarieEtienne** [comment]
Also be careful you remove all the files produced by other groups. if you merge this into master, you will remove all the works from others

**Comment by MarieEtienne** [comment]
Start fresh from master  by creatin a new branch, 
switch -c fix_master

**Pull request closed without merging**
